Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
Can't load history: $< line too long.
Now running source localization for CA152
LOADEDMODULES=pbspro:Anaconda3-5.1.0 ;export LOADEDMODULES;PATH=/usr/physics/python/anaconda3/bin:/usr/lib64/qt-3.3/bin:/headnode1/abry4213/software/freesurfer/bin:/headnode1/abry4213/software/freesurfer/fsfast/bin:/headnode1/abry4213/software/freesurfer/bin:/headnode1/abry4213/.vscode-server/cli/servers/Stable-31c37ee8f63491495ac49e43b8544550fbae4533/server/bin/remote-cli:/usr/physics/pbspro/bin:/headnode1/abry4213/bin:/usr/physics/bin:/bin:/usr/local/bin:/usr/share/Modules/bin:/usr/bin:/opt/dell/srvadmin/bin:/usr/local/sbin:/usr/sbin ;export PATH;_LMFILES_=/usr/physics/share/modulefiles/pbspro:/usr/physics/share/modulefiles/Anaconda3-5.1.0 ;export _LMFILES_;Traceback (most recent call last):
  File "/headnode1/abry4213/github/cogitate-msp1/coglib/meeg/source_modelling/S00a_scalp_surfaces.py", line 116, in <module>
    make_scalp_surf()
  File "/headnode1/abry4213/github/cogitate-msp1/coglib/meeg/source_modelling/S00a_scalp_surfaces.py", line 106, in make_scalp_surf
    mnebem.make_scalp_surfaces(subject, 
  File "<decorator-gen-71>", line 22, in make_scalp_surfaces
  File "/headnode1/abry4213/.conda/envs/pyspi/lib/python3.9/site-packages/mne/bem.py", line 2099, in make_scalp_surfaces
    raise RuntimeError('%s does not exist. Please check your subject '
RuntimeError: /headnode1/abry4213/data/Cogitate_Batch2/MEG_Data/derivatives/fs/sub-CA152 does not exist. Please check your subject directory path.
Can't load history: $< line too long.
